# Generated by Django 3.0.1 on 2020-01-04 21:05

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name', 'instructions'], name='app_recipe_name_c81ea9_gin'),
        ),
    ]
