# Generated by Django 3.0.1 on 2020-01-09 18:35

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(default=None),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='app_recipe_search__7e0f6e_gin'),
        ),
    ]
