# Generated by Django 3.0.1 on 2020-01-10 17:22
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations
from joc.settings import POSTGRES_LANGUAGE_UNACCENT


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200110_1412'),
    ]

    # https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/lookups/#trigram-similarity
    operations = [
        TrigramExtension(),
        UnaccentExtension(),
        migrations.RunSQL(
            # create a custom unaccented language configuration
            "CREATE TEXT SEARCH CONFIGURATION {} ( COPY = french )".format(POSTGRES_LANGUAGE_UNACCENT),
            "ALTER TEXT SEARCH CONFIGURATION {} ALTER MAPPING FOR hword, hword_part, word WITH unaccent, simple".format(POSTGRES_LANGUAGE_UNACCENT),
        )
    ]
