# Generated by Django 3.0.1 on 2020-01-10 17:22
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations
from joc.settings import POSTGRES_LANGUAGE_UNACCENT


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200110_1412'),
    ]

    operations = [
        # https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/lookups/#trigram-similarity
        TrigramExtension(),
        # https://docs.djangoproject.com/en/3.0/ref/contrib/postgres/lookups/#unaccent
        UnaccentExtension(),
        # create a custom unaccented language configuration
        migrations.RunSQL("CREATE TEXT SEARCH CONFIGURATION {} ( COPY = english )".format(POSTGRES_LANGUAGE_UNACCENT)),
        migrations.RunSQL("ALTER TEXT SEARCH CONFIGURATION {} ALTER MAPPING FOR hword, hword_part, word WITH unaccent, english_stem".format(POSTGRES_LANGUAGE_UNACCENT)),
    ]
